name: ci
on:
    pull_request:

jobs:
    check_corrections:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Fetch deps
              run: |
                set -e
                sudo apt-get -q update
                sudo apt-get install -y jq make

            - name: Check corrections.json for syntax errors
              run: jq . <corrections.json >/dev/null

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.24.6

            - name: Build mmdb-editor
              run: |
                set -e
                git clone https://github.com/iglov/mmdb-editor.git
                cd mmdb-editor
                make linux-amd64
                cd ..

            - name: Fetch base db
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                set -e
                gh release download latest -p city-lite-base.mmdb.gz
                gunzip city-lite-base.mmdb.gz

            - name: Apply corrections
              run: |
                mmdb-editor/bin/mmdb-editor* -d corrections.json -i city-lite-base.mmdb -o city-lite.mmdb
