name: merge

on:
    push:
        branches:
            - main

jobs:
    apply-corrections:
        uses: ./.github/workflows/apply-corrections.yml
        with:
            upload-db: true
        secrets: inherit

    release-db:
        runs-on: ubuntu-latest
        if: github.repository == 'openhtc/geoipdb'
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: city-lite

            - name: Upload it to release
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                gh release upload latest city-lite.mmdb.gz --clobber
