name: merge

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        if: github.repository == 'openhtc/geoipdb'
        steps:
            - name: Download artifact from ci
              uses:
                dawidd6/action-download-artifact@v11
              with:
                workflow_search: true
                branch: main
                use_unzip: true

            - name: Upload it to release
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                gh release upload latest city-lite.mmdb.gz --clobber
